package com.mycompany.pawsshop.ui;

import com.mycompany.pawsshop.data.Item;
import com.mycompany.pawsshop.other.DataPersistence;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mihin
 */
public class StoreFrame extends javax.swing.JFrame {

    private ArrayList<Item> items = new ArrayList<>();
    private DefaultTableModel tableModel;

    /**
     * Creates new form StoreFrame
     */
    public StoreFrame() {
        initComponents();
        tableModel = new DefaultTableModel(new Object[]{"Item Category", "Total Items", "Item Price", "Supplier Name", "Supplier Payment"}, 0);
        storeViewTable.setModel(tableModel);

        // Load items from the file
        items = DataPersistence.loadItems();

        if (items.isEmpty()) {
            System.out.println("No items found in file.");
        } else {
            System.out.println("Loaded items:");
            for (Item item : items) {
                System.out.println(item.getCategory() + " | " + item.getSupplierName());
            }
        }

        // Populate the table with the loaded data
        for (Item item : items) {
            tableModel.addRow(new Object[]{
                item.getCategory(),
                item.getTotalItems(),
                item.getPrice(),
                item.getSupplierName(),
                item.getPayment()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search_CatagorySelection = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_suppliername = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        txt_totalItem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_payment = new javax.swing.JTextField();
        CatagorySelection = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        storeViewTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        backBtn = new javax.swing.JToggleButton();
        btn_logout = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_download = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Store");

        jLabel2.setText("Select Item Category :");

        search_CatagorySelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toys", "Foods", "Grooming", "Harnesses", "Cages", "Collars" }));
        search_CatagorySelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_CatagorySelectionActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Items : ");

        jLabel5.setText("Item Supplier Name :");

        SearchBtn.setBackground(new java.awt.Color(0, 204, 204));
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Search items ");

        addBtn.setBackground(new java.awt.Color(0, 204, 204));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(0, 204, 204));
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setBackground(new java.awt.Color(0, 204, 204));
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Item Price :");

        jLabel8.setText("Supplier Payment :");

        CatagorySelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toys", "Foods", "Grooming", "Harnesses", "Cages", "Collars" }));
        CatagorySelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatagorySelectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_suppliername, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateBtn)
                .addGap(18, 18, 18)
                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_price)
                    .addComponent(CatagorySelection, 0, 145, Short.MAX_VALUE)
                    .addComponent(txt_totalItem))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(103, 103, 103))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(search_CatagorySelection, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchBtn)
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(search_CatagorySelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CatagorySelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_totalItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(UpdateBtn)
                            .addComponent(DeleteBtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_suppliername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        storeViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Category", "Total Items", "Item Price", "Supplier Name", "Supplier Payment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        storeViewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storeViewTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(storeViewTable);

        jLabel9.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+ "\\src\\main\\java\\images\\petimage4.png"));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_refresh.setBackground(new java.awt.Color(0, 204, 204));
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_download.setBackground(new java.awt.Color(0, 204, 204));
        btn_download.setText("Download");
        btn_download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_downloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(btn_refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_download)
                        .addGap(37, 37, 37)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(btn_logout))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_refresh)
                                    .addComponent(btn_download)))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_CatagorySelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_CatagorySelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_CatagorySelectionActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        String selectedCategory = (String) search_CatagorySelection.getSelectedItem();  // Get selected category

        // Clear existing rows in the table
        tableModel.setRowCount(0);

        // Iterate through the items and add those matching the selected category to the table
        for (Item item : items) {
            if (item.getCategory().equalsIgnoreCase(selectedCategory)) {  // Match category (case insensitive)
                tableModel.addRow(new Object[]{
                    item.getCategory(),
                    item.getTotalItems(),
                    item.getPrice(),
                    item.getSupplierName(),
                    item.getPayment()
                });
            }
        }

        // If no item matches the selected category, you can optionally show a message
        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No items found for the selected category.", "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String category = (String) search_CatagorySelection.getSelectedItem();
        String payment = txt_payment.getText();
        String price = txt_price.getText();
        String supplierName = txt_suppliername.getText();
        String totalItem = txt_totalItem.getText();

        double paymentAmount = Double.parseDouble(payment);
        double itemPrice = Double.parseDouble(price);
        int totalItems = Integer.parseInt(totalItem);

        // Create the new Item object
        Item newItem = new Item(supplierName, category, itemPrice, paymentAmount, totalItems);

        // Add the new item to the items list
        items.add(newItem);

        // Add the new item directly to the table
        DefaultTableModel model = (DefaultTableModel) storeViewTable.getModel();
        Object[] row = new Object[]{category, totalItems, itemPrice, supplierName, paymentAmount};
        model.addRow(row);

        // Save the updated items list to the file
        DataPersistence.saveItems(items);
        clearFields();

        JOptionPane.showMessageDialog(this, "Item added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        int selectedRow = storeViewTable.getSelectedRow();

        // Check if any row is selected
        if (selectedRow != -1) {
            // Get the supplier name (or any other unique field) of the selected item
            String supplierName = storeViewTable.getValueAt(selectedRow, 3).toString();

            // Remove the item from the items list based on the supplier name
            items.removeIf(item -> item.getSupplierName().equals(supplierName));

            // Remove the selected row from the table
            DefaultTableModel model = (DefaultTableModel) storeViewTable.getModel();
            model.removeRow(selectedRow);

            // Save the updated items list to the file
            DataPersistence.saveItems(items);

            JOptionPane.showMessageDialog(this, "Item deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Please select an item to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        int selectedRow = storeViewTable.getSelectedRow();

        // Check if any row is selected
        if (selectedRow != -1) {
            // Get the current values of the selected item
            String currentCategory = storeViewTable.getValueAt(selectedRow, 0).toString();
            int currentTotalItems = (int) storeViewTable.getValueAt(selectedRow, 1);
            double currentItemPrice = (double) storeViewTable.getValueAt(selectedRow, 2);
            String currentSupplierName = storeViewTable.getValueAt(selectedRow, 3).toString();
            double currentPaymentAmount = (double) storeViewTable.getValueAt(selectedRow, 4);

            // Retrieve new data from the text fields
            String newCategory = (String) search_CatagorySelection.getSelectedItem();
            String newPayment = txt_payment.getText();
            String newPrice = txt_price.getText();
            String newSupplierName = txt_suppliername.getText();
            String newTotalItem = txt_totalItem.getText();

            double newPaymentAmount = Double.parseDouble(newPayment);
            double newItemPrice = Double.parseDouble(newPrice);
            int newTotalItems = Integer.parseInt(newTotalItem);

            // Find and update the item in the items list
            for (Item item : items) {
                if (item.getSupplierName().equals(currentSupplierName)) {
                    item.setCategory(newCategory);
                    item.setPrice(newItemPrice);
                    item.setPayment(newPaymentAmount);
                    item.setTotalItems(newTotalItems);

                    // Update the table row
                    DefaultTableModel model = (DefaultTableModel) storeViewTable.getModel();
                    model.setValueAt(newCategory, selectedRow, 0);
                    model.setValueAt(newTotalItems, selectedRow, 1);
                    model.setValueAt(newItemPrice, selectedRow, 2);
                    model.setValueAt(newSupplierName, selectedRow, 3);
                    model.setValueAt(newPaymentAmount, selectedRow, 4);

                    break;
                }
            }

            // Save the updated items list to the file
            DataPersistence.saveItems(items);

            clearFields();

            JOptionPane.showMessageDialog(this, "Item updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Please select an item to update.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        SuppliersFrame suppliersFrame = new SuppliersFrame();
        suppliersFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void storeViewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeViewTableMouseClicked
// Get the selected row index
        int selectedRow = storeViewTable.getSelectedRow();

        if (selectedRow != -1) { // Check if a valid row is selected

            // Get the values from the selected row
            String category = storeViewTable.getValueAt(selectedRow, 0).toString();
            int totalItems = Integer.parseInt(storeViewTable.getValueAt(selectedRow, 1).toString());
            double price = Double.parseDouble(storeViewTable.getValueAt(selectedRow, 2).toString());
            String supplierName = storeViewTable.getValueAt(selectedRow, 3).toString();
            double payment = Double.parseDouble(storeViewTable.getValueAt(selectedRow, 4).toString());

            // Populate the fields with the selected row's data
            CatagorySelection.setSelectedItem(category);  // Populate the category dropdown
            txt_totalItem.setText(String.valueOf(totalItems));    // Populate total items text field
            txt_price.setText(String.valueOf(price));              // Populate price text field
            txt_suppliername.setText(supplierName);                // Populate supplier name text field
            txt_payment.setText(String.valueOf(payment));          // Populate payment text field
        }
    }//GEN-LAST:event_storeViewTableMouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // Clear existing rows in the table
        tableModel.setRowCount(0);

        // Add all items back to the table
        for (Item item : items) {
            tableModel.addRow(new Object[]{
                item.getCategory(),
                item.getTotalItems(),
                item.getPrice(),
                item.getSupplierName(),
                item.getPayment()
            });
        }
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_downloadActionPerformed
        File file = new File("downloaded_items_data.txt");

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            // Write a header line (optional)
            writer.write("Item Category\tTotal Items\tItem Price\tSupplier Name\tSupplier Payment");
            writer.newLine();

            // Iterate over the items list and write each item to the file
            for (Item item : items) {
                writer.write(item.getCategory() + "\t" + item.getTotalItems() + "\t"
                        + item.getPrice() + "\t" + item.getSupplierName() + "\t"
                        + item.getPayment());
                writer.newLine();
            }

            // Inform the user that the data has been saved
            JOptionPane.showMessageDialog(this, "Data has been saved to " + file.getAbsolutePath(), "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            // Handle any errors during file writing
            JOptionPane.showMessageDialog(this, "Error saving data to file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_downloadActionPerformed

    private void CatagorySelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatagorySelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatagorySelectionActionPerformed

    private void clearFields() {
        // Clear all input fields after adding the item
        search_CatagorySelection.setSelectedIndex(0);
        txt_payment.setText("");
        txt_price.setText("");
        txt_suppliername.setText("");
        txt_totalItem.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CatagorySelection;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JToggleButton SearchBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JToggleButton backBtn;
    private javax.swing.JButton btn_download;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> search_CatagorySelection;
    private javax.swing.JTable storeViewTable;
    private javax.swing.JTextField txt_payment;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_suppliername;
    private javax.swing.JTextField txt_totalItem;
    // End of variables declaration//GEN-END:variables
}
